### PR TITLE
Rename low-level bit manipulation functions

### PR DESCRIPTION
**Pull request by cwharris**
Updates low-level bit manipulation functions as described in [wg21.link/P1956R1](wg21.link/P1956R1).

### CODE REVIEW

**Review by brycelelbach — APPROVED** [review]
This looks fine to me. We should perhaps consider exposing this up in `cuda::std::`.

**Comment by cwharris** [comment]
How does one go about merging?

**Comment by brycelelbach** [comment]
@griwes to merge this.

**Comment by cwharris** [comment]
Any changes need to be made here?

**Comment by wmaxey** [comment]
I've forgotten about this PR, I will try to merge this.

**Comment by wmaxey** [comment]
This has been merged in #237.

**Pull request closed without merging**
