### PR TITLE
Polymorphic Allocator Proposal 

### PR DESCRIPTION
**Pull request by jrhemstad**
Design: #129

Depends on #105

Building of off [`cuda::memory_resource`](https://github.com/NVIDIA/libcudacxx/pull/105) to introduce `cuda::polymorphic_allocator`-like types

### CODE REVIEW

**Comment by brycelelbach** [comment]
I'd really rather not call it `polymorphic`. It's a bad name, it's not important for the user to know that, and some classes of performance-sensitive users are allergic to polymorphism even if it's not relevant to performance (as is the case here).

**Comment by jrhemstad** [comment]
> I'd really rather not call it `polymorphic`. It's a bad name, it's not important for the user to know that, and some classes of performance-sensitive users are allergic to polymorphism even if it's not relevant to performance (as is the case here).

I have no qualms with axing the "polymorphic" part of the name. Would we just call it `cuda::allocator` and it always works with a `memory_resource*`?

**Comment by brycelelbach** [comment]
I'm in favor of `cuda::allocator`.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/NVIDIA/libcudacxx/pull/309

**Pull request closed without merging**
