### PR TITLE
Making python code pythonic

### PR DESCRIPTION
**Pull request by LukasMoll**
Applied PEP 8 code conventions, removed unused code, fixed small warnings etc.

### CODE REVIEW

**Comment by wmaxey** [comment]
This is a large diff and may take some time to review. First glance, thanks this is some helpful cleanup.

**Comment by jrhemstad** [comment]
Hey @LukasMoll, thanks for looking to help us out! 

We'd be open to adding a pre-commit configuration for automatic code formatting (I'm actively working on this for the C++ source), but all of these Python files come from upstream repositories (libc++) and we don't want to modify them to maintain consistency with their sources.

**Comment by LukasMoll** [comment]
@wmaxey 
I could split it into multiple PRs if you want.

**Comment by LukasMoll** [comment]
@jrhemstad 
Yes, all code seems to come from another place.
I could still add a pre-commit configuration if you want.

**Pull request closed without merging**
