### PR TITLE
Fix numerics of complex exp at inf

### PR DESCRIPTION
**Pull request by zasdfgbnm**
Test:
```C++
#include <complex>
#include <cuda/std/complex>
#include <iostream>

int main() {
    float rvalues[] = {501, -501};
    float ivalues[] = {0, -0};
    for (float r : rvalues) {
        for (float i : ivalues) {
            std::complex<float> s = {r, i};
            cuda::std::complex<float> c = {r, i};

            auto ts = std::exp(s);
            auto tc = cuda::std::exp(c);

            std::cout << "input: (" << r << ", " << i << ")" << std::endl;
            std::cout << "std: (" << ts.real() << ", " << ts.imag() << ")" << std::endl;
            std::cout << "cuda::std: (" << tc.real() << ", " << tc.imag() << ")" << std::endl;
            std::cout << std::endl;
        }
    }
}
```

Before
```
input: (501, 0)
std: (inf, 0)
cuda::std: (inf, -nan)

input: (501, 0)
std: (inf, 0)
cuda::std: (inf, -nan)

input: (-501, 0)
std: (0, 0)
cuda::std: (0, 0)

input: (-501, 0)
std: (0, 0)
cuda::std: (0, 0)
```

After:
```
input: (501, 0)
std: (inf, 0)
cuda::std: (inf, 0)

input: (501, 0)
std: (inf, 0)
cuda::std: (inf, 0)

input: (-501, 0)
std: (0, 0)
cuda::std: (0, 0)

input: (-501, 0)
std: (0, 0)
cuda::std: (0, 0)
```

Thanks a lot cc @mruberry @ngimel for discussion.

### CODE REVIEW

**Comment by zasdfgbnm** [comment]
Upstream diff: https://reviews.llvm.org/D112277

**Comment by zasdfgbnm** [comment]
I updated this PR according to upstream. BTW, how do I run tests locally? I was trying to compile, but get error:

```
-- Check for working C compiler: /usr/local/cuda/bin/g++ - broken
CMake Error at /home/gaoxiang/.local/lib/python3.9/site-packages/cmake/data/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/local/cuda/bin/g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/gaoxiang/libcudacxx/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_0381e/fast && /usr/bin/make  -f CMakeFiles/cmTC_0381e.dir/build.make CMakeFiles/cmTC_0381e.dir/build
    make[1]: Entering directory '/home/gaoxiang/libcudacxx/build/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_0381e.dir/testCCompiler.c.o
    /usr/local/cuda/bin/g++    -o CMakeFiles/cmTC_0381e.dir/testCCompiler.c.o -c /home/gaoxiang/libcudacxx/build/CMakeFiles/CMakeTmp/testCCompiler.c
    /home/gaoxiang/libcudacxx/build/CMakeFiles/CMakeTmp/testCCompiler.c:2:3: error: #error "The CMAKE_C_COMPILER is set to a C++ compiler"
        2 | # error "The CMAKE_C_COMPILER is set to a C++ compiler"
          |   ^~~~~
    make[1]: *** [CMakeFiles/cmTC_0381e.dir/build.make:85: CMakeFiles/cmTC_0381e.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/gaoxiang/libcudacxx/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:140: cmTC_0381e/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (enable_language)
```

**Comment by griwes** [comment]
See https://nvidia.github.io/libcudacxx/setup/building_and_testing.html.

**Comment by zasdfgbnm** [comment]
Thanks @griwes for the help. I am able to locally run the tests, and this PR should be ready now.

**Comment by wmaxey** [comment]
Submitted tests under CL 30743870

**Review by wmaxey — APPROVED** [review]

**Pull request merged**
