### PR TITLE
Add docker files for 16 configs 

### PR DESCRIPTION
**Pull request by veictry**
### Config
- Arch: x86_64
- Compiler: HPC | GCC 11 | NVRTC

### DVSSC Virtual:
- HPC: https://scbuilds4u/dvs/#/change/3116046839432407.1?eventType=Virtual
- GCC 11: https://scbuilds4u/dvs/#/change/3116077939432407.2?eventType=Virtual
- NVRTC: http://scbuilds4u.nvidia.com/dvs/#/change/3116084339432407.1?showTab=DVS (failed with libcudacxx issue)

### CODE REVIEW

**Comment by wmaxey** [comment]
I have one complaint: We don't target platforms for testing; we target compilers. So if Ubuntu+GCC11 already cover a test we don't need fedora+GCC11.

Would it be possible to remove overlaps?

**Comment by veictry** [comment]
Hi @wmaxey 
I don't find GCC 11 docker file in docker/host_x86_64/...
is there something I missed?

**Comment by veictry** [comment]
I found that there are some wrong command during libcxx build:
```docker
RUN set -o pipefail; cd /sw/gpgpu/libcudacxx/libcxx/build\
 && cmake ../..\
 -DLIBCUDACXX_ENABLE_STATIC_LIBRARY=OFF\
 -DLIBCUDACXX_ENABLE_LIBCUDACXX_TESTS=OFF\
 -DLIBCUDACXX_ENABLE_LIBCXX_TESTS=ON\
 -DLIBCXX_TEST_STANDARD_VER=c++$COMPILER_CXX_DIALECT\
 -DCMAKE_CXX_COMPILER=g++\   <==================
 -DCMAKE_CUDA_COMPILER=/sw/gpgpu/bin/x86_64_Linux_release/nvcc\ <==================
 && make -j\
 2>&1 | tee /sw/gpgpu/libcudacxx/build/cmake_libcxx.log
```

**Comment by veictry** [comment]
Hi @wmaxey 
I tried to run libcxx build with the below command but failed:
```
# Build libc++ and configure libc++ tests.
RUN set -o pipefail; cd /sw/gpgpu/libcudacxx/libcxx/build\
 && cmake ../..\
 -DLIBCUDACXX_ENABLE_STATIC_LIBRARY=OFF\
 -DLIBCUDACXX_ENABLE_LIBCUDACXX_TESTS=OFF\
 -DLIBCUDACXX_ENABLE_LIBCXX_TESTS=ON\
 -DLIBCXX_TEST_STANDARD_VER=c++$COMPILER_CXX_DIALECT\
 -DCMAKE_CXX_COMPILER=g++\
 -DCMAKE_CUDA_COMPILER=/sw/gpgpu/bin/x86_64_Linux_release/nvcc\
 && make -j\
 2>&1 | tee /sw/gpgpu/libcudacxx/build/cmake_libcxx.log
```
Error Message
```
2022-04-05 04:58:03-07:00| -- Performing Test LIBCXX_SUPPORTS_STD_COLON_CXX11_FLAG - Failed
2022-04-05 04:58:03-07:00| [91mCMake Error at libcxx/CMakeLists.txt:539 (message):
2022-04-05 04:58:03-07:00| C++11 or greater is required but the compiler does not support c++11
2022-04-05 04:58:03-07:00| Call Stack (most recent call first):
2022-04-05 04:58:03-07:00| libcxx/src/CMakeLists.txt:237 (cxx_add_basic_build_flags)
2022-04-05 04:58:03-07:00| 
2022-04-05 04:58:03-07:00| 
2022-04-05 04:58:03-07:00| [0m-- Configuring incomplete, errors occurred!
```
 
Is there any suggestion about it?
I'd like to comment  our these build command temporarily.

**Comment by veictry** [comment]
I created docker files for those compilers. 
Could I submit all of them in just one git commit?

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Arch | Compiler | Link | Status
-- | -- | -- | --
x86_64 | GCC 11 | https://scbuilds4u/dvs/#/change/3115976339432407.1?eventType=Virtual | OK
x86_64 | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3116788639432407.2?showTab=DVS |  
x86_64 | NVRTC | http://scbuilds4u.nvidia.com/dvs/#/change/3116681639432407.3?showTab=DVS |  
arm64 | GCC 8 | http://scbuilds4u.nvidia.com/dvs/#/change/3116676539432407.1?showTab=DVS |  
arm64 | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3116789739432407.1?showTab=DVS |  
arm64 | NVRTC | http://scbuilds4u.nvidia.com/dvs/#/change/3116796739432407.1?showTab=DVS |  
arm64 | Clang   12 | http://scbuilds4u.nvidia.com/dvs/#/change/3116683539432407.1?showTab=DVS |  
arm64 | Clang   13 | http://scbuilds4u.nvidia.com/dvs/#/change/3116683539432407.1?showTab=DVS |  
arm64 | armclang | http://scbuilds4u.nvidia.com/dvs/#/change/3116695539432407.1?showTab=DVS |  
arm64 | armgcc | http://scbuilds4u.nvidia.com/dvs/#/change/3116695539432407.1?showTab=DVS |  
ppc64le | GCC 8 | http://scbuilds4u.nvidia.com/dvs/#/change/3116632539432407.1?showTab=DVS |  
ppc64le | Clang   12 | http://scbuilds4u.nvidia.com/dvs/#/change/3116632539432407.1?showTab=DVS | OK
ppc64le | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3116762839432407.2?showTab=DVS |  
x86_64 | GCC 11   C++20 | http://scbuilds4u.nvidia.com/dvs/#/change/3116715139432407.1?showTab=DVS | OK
x86_64 | Clang   14 | http://scbuilds4u.nvidia.com/dvs/#/change/3116801739432407.1?showTab=DVS |  



</div>


</body>

</html>

**Comment by veictry** [comment]
I submitted other docker files in one commit. please help review them.

all DVS-SC build:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=zh-CN style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Arch | Compiler | Link | Status
-- | -- | -- | --
x86_64 | GCC 11 | https://scbuilds4u/dvs/#/change/3115976339432407.1?eventType=Virtual | OK
x86_64 | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3116788639432407.2?showTab=DVS | OK
x86_64 | NVRTC | http://scbuilds4u.nvidia.com/dvs/#/change/3116681639432407.3?showTab=DVS | OK
arm64 | GCC 8 | http://scbuilds4u.nvidia.com/dvs/#/change/3116830139432407.3?showTab=DVS |  
arm64 | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3117049939432407.1?showTab=DVS |  
arm64 | NVRTC | http://scbuilds4u.nvidia.com/dvs/#/change/3116796739432407.1?showTab=DVS | OK
arm64 | Clang   12 | http://scbuilds4u.nvidia.com/dvs/#/change/3116683539432407.1?showTab=DVS | OK
arm64 | Clang   13 | http://scbuilds4u.nvidia.com/dvs/#/change/3116683539432407.1?showTab=DVS | OK
arm64 | armclang | http://scbuilds4u.nvidia.com/dvs/#/change/3116695539432407.1?showTab=DVS | OK
arm64 | armgcc | http://scbuilds4u.nvidia.com/dvs/#/change/3116695539432407.1?showTab=DVS | OK
ppc64le | GCC 8 | http://scbuilds4u.nvidia.com/dvs/#/change/3116632539432407.1?showTab=DVS | OK
ppc64le | Clang   12 | http://scbuilds4u.nvidia.com/dvs/#/change/3116632539432407.1?showTab=DVS | OK
ppc64le | HPC | http://scbuilds4u.nvidia.com/dvs/#/change/3116762839432407.2?showTab=DVS | OK
x86_64 | GCC 11   C++20 | http://scbuilds4u.nvidia.com/dvs/#/change/3116715139432407.1?showTab=DVS | OK
x86_64 | Clang   14 | http://scbuilds4u.nvidia.com/dvs/#/change/3116837439432407.1?showTab=DVS | OK
x86_64 | MSVC | http://scbuilds4u.nvidia.com/dvs/#/change/3116523939432407.1?showTab=DVS | OK



</div>


</body>

</html>

**Comment by wmaxey** [comment]
There have been a few changes to the Dockerfiles recently that will effect these, but I have some scripts I previously used to make those changes. I've replicated them here.

`ADD cuda/tools/libcudacxxext /sw/gpgpu/cuda/tools/libcudacxxext` has been removed. We own the files in this directory now. Additionally other CUDART headers have been packaged along with compiler, I believe we can remove those.

```
# Remove comment from section of dockerfile.
sed -i "\#.*Copy the core CUDA#d" $(find docker -iname "*dockerfile")
# Remove various sw/gpgpu files from dockerfile.
sed -i "\#ADD cuda/.* /sw/gpgpu/cuda/.*#d" $(find docker -iname "*dockerfile")
sed -i "\#ADD opencl/*#d" $(find docker -iname "*dockerfile")
sed -i "\#ADD cuda/tools/libcudacxxext /sw/gpgpu/cuda/tools/libcudacxxext#d" $(find docker -iname "*dockerfile")
```

**Comment by wmaxey** [comment]
> Hi @wmaxey I don't find GCC 11 docker file in docker/host_x86_64/... is there something I missed?

My apologies, I hadn't realized it was already covered.

**Comment by wmaxey** [comment]
These changes overall look good, I'll approve once the fixes I suggested are applied to this PR.

**Comment by miscco** [comment]
@wmaxey Do we still want this given the recent docker rework?

**Comment by wmaxey** [comment]
I don't think so. If there's a need @veictry or @chengjiew can DM me and we can look at adding them.

**Pull request closed without merging**
