### PR TITLE
_LIBCUDACXX_CUDACC_VER major value needs to be computed as the seventh digit

### PR DESCRIPTION
**Pull request by robertmaynard**
The introduction of an extra digit to handle minor CUDACC versions greater than 100 forgot to also increment the major value. Since this meant that all values of _LIBCUDACXX_CUDACC_VER stayed as 6 digits, but we compared against 7 digit values no CUDA versions reported decimal 128 support.

### CODE REVIEW

**Comment by jrhemstad** [comment]
Yeesh, math is hard. I think this is the 4th time we've had to correct this :) 

Makes me feel like we should abandon trying to have a single representative number for the CUDA version. Is there an easier way to write <11.5 by just looking at the major/minor components?   
```
#if defined(_LIBCUDACXX_COMPILER_MSVC) || (defined(_LIBCUDACXX_CUDACC_VER) && ((_LIBCUDACXX_CUDACC_VER_MAJOR < 11) ||  (_LIBCUDACXX_CUDACC_VER_MAJOR == 11 && _LIBCUDACXX_CUDACC_VER_MINOR < 5)) )
#  define _LIBCUDACXX_HAS_NO_INT128
#endif

**Comment by robertmaynard** [comment]
> Yeesh, math is hard. I think this is the 4th time we've had to correct this :)
> 
> Makes me feel like we should abandon trying to have a single representative number for the CUDA version. Is there an easier way to write <11.5 by just looking at the major/minor components?
> 
> ```
> #if defined(_LIBCUDACXX_COMPILER_MSVC) || (defined(_LIBCUDACXX_CUDACC_VER) && ((_LIBCUDACXX_CUDACC_VER_MAJOR < 11) ||  (_LIBCUDACXX_CUDACC_VER_MAJOR == 11 && _LIBCUDACXX_CUDACC_VER_MINOR < 5)) )
> #  define _LIBCUDACXX_HAS_NO_INT128
> #endif
> ```

That is a possibility. I don't know what libcudacxx back-compat policy is, but we might need to keep _LIBCUDACXX_CUDACC_VER as a 6 digit number and use your check

**Comment by wmaxey** [comment]
Nobody should be using this value downstream. It's certainly not documented. It's purely an internal computation.

Visually I'd prefer the above solution, but the one submitted by @jrhemstad is something we do already elsewhere.

from `<cuda/std/chrono>`:
```
#if defined(_LIBCUDACXX_COMPILER_NVCC)
#  if (CUDART_VERSION >= 11050)
#    pragma nv_diag_suppress cuda_demote_unsupported_floating_point
#  else
#    pragma diag_suppress cuda_demote_unsupported_floating_point
#  endif
#endif
```

**Comment by robertmaynard** [comment]
> Nobody should be using this value downstream. It's certainly not documented. It's purely an internal computation.
> 
> Visually I'd prefer the above solution, but I noticed a change I made elsewhere that has a competing idea.
> 
> from `<cuda/std/chrono>`:
> 
> ```
> #if defined(_LIBCUDACXX_COMPILER_NVCC)
> #  if (CUDART_VERSION >= 11050)
> #    pragma nv_diag_suppress cuda_demote_unsupported_floating_point
> #  else
> #    pragma diag_suppress cuda_demote_unsupported_floating_point
> #  endif
> #endif
> ```

The current usage of __CUDACC_VER_MAJOR__ / __CUDACC_VER_MINOR__ captures both clang and nvcc, while moving over to _LIBCUDACXX_COMPILER_NVCC would drop clang. Now that actually might be desired as I don't know if clang + cuda 11.5 is sufficient for decimal 128 support.

**Comment by wmaxey** [comment]
Right, I would be wary of presuming it for other compilers. I'm happy to stick with the current solution.

**Review by wmaxey — APPROVED** [review]

**Pull request merged**
